version: "3.9"
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
    - data:/data
    ports:
    - 8080:8080
    env_file:
      - .env.docker
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    env_file:
      - .env.docker
volumes:
  data: